### ISSUE TITLE
Jupyter notebooks

### ISSUE THREAD

**Issue by aquilesC** [Wookai/paper-tips-and-tricks#5]
What about the use of Jupyter notebooks for generating figures?

**Comment by Wookai** [comment]
I do use notebooks a lot to iterate quickly on the figures and come up with the right way of presenting data, however once I'm done I prefer to have the code in a Python script. It makes it easier to run things in one click and possibly automate stuff (e.g. have a makefile which regenerates all figures and then compiles the document).
